/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetopi;

import Controlle.Validador;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author janaina.csilva64
 */
public class Cadastro extends javax.swing.JFrame {

    private Validador validador;

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();

        validador = new Validador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        SeCadastro = new javax.swing.JTabbedPane();
        EnderecoCli = new javax.swing.JPanel();
        Numero = new javax.swing.JLabel();
        Rua = new javax.swing.JLabel();
        Bairro = new javax.swing.JLabel();
        Cidade = new javax.swing.JLabel();
        UF = new javax.swing.JLabel();
        CEP = new javax.swing.JLabel();
        Pais = new javax.swing.JLabel();
        NumeroCli = new javax.swing.JTextField();
        RuaCli = new javax.swing.JTextField();
        BairroCli = new javax.swing.JTextField();
        CidadeCli = new javax.swing.JTextField();
        PaisCli = new javax.swing.JTextField();
        UFCli = new javax.swing.JFormattedTextField();
        CepCli = new javax.swing.JFormattedTextField();
        ContinuarEndereco = new javax.swing.JButton();
        VoltarEndereco = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CV = new javax.swing.JLabel();
        Validade = new javax.swing.JLabel();
        Bandeira = new javax.swing.JLabel();
        NumeroCartaoCli = new javax.swing.JFormattedTextField();
        CVCli = new javax.swing.JFormattedTextField();
        ValidadeCli = new javax.swing.JFormattedTextField();
        ContinuarDadosBancarios = new javax.swing.JButton();
        VoltarDadosBancarios = new javax.swing.JButton();
        BandeiraCli = new javax.swing.JComboBox<>();
        CadCliente = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        CPF = new javax.swing.JLabel();
        DataNascimento = new javax.swing.JLabel();
        NomeCli = new javax.swing.JTextField();
        Confirmar = new javax.swing.JButton();
        VoltarCadCli = new javax.swing.JButton();
        Telefone = new javax.swing.JLabel();
        DataNascimentoCli = new javax.swing.JFormattedTextField();
        CPFCli = new javax.swing.JFormattedTextField();
        TelefoneCli = new javax.swing.JFormattedTextField();
        Email = new javax.swing.JLabel();
        EmailCli = new javax.swing.JTextField();
        MnCadastro = new javax.swing.JMenuBar();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Numero.setText("Numero:");

        Rua.setText("Rua:");

        Bairro.setText("Bairro:");

        Cidade.setText("Cidade:");

        UF.setText("UF:");

        CEP.setText("CEP:");

        Pais.setText("País:");

        BairroCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BairroCliActionPerformed(evt);
            }
        });

        try {
            UFCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            CepCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ContinuarEndereco.setText("Continuar");
        ContinuarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarEnderecoActionPerformed(evt);
            }
        });

        VoltarEndereco.setText("Voltar");
        VoltarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EnderecoCliLayout = new javax.swing.GroupLayout(EnderecoCli);
        EnderecoCli.setLayout(EnderecoCliLayout);
        EnderecoCliLayout.setHorizontalGroup(
            EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnderecoCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnderecoCliLayout.createSequentialGroup()
                        .addGroup(EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Numero)
                            .addComponent(Rua)
                            .addComponent(Bairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RuaCli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(BairroCli, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumeroCli)))
                    .addGroup(EnderecoCliLayout.createSequentialGroup()
                        .addGroup(EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cidade)
                            .addComponent(Pais)
                            .addComponent(UF)
                            .addComponent(CEP))
                        .addGap(18, 18, 18)
                        .addGroup(EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(UFCli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(PaisCli, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CidadeCli, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CepCli))))
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnderecoCliLayout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(VoltarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContinuarEndereco)
                .addContainerGap())
        );
        EnderecoCliLayout.setVerticalGroup(
            EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnderecoCliLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero)
                    .addComponent(NumeroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rua)
                    .addComponent(RuaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bairro)
                    .addComponent(BairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cidade)
                    .addComponent(CidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pais)
                    .addComponent(PaisCli, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UF)
                    .addComponent(UFCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CEP)
                    .addComponent(CepCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EnderecoCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoltarEndereco)
                    .addComponent(ContinuarEndereco))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        SeCadastro.addTab("Endereço", EnderecoCli);

        jLabel1.setText("Numero do cartão:");

        CV.setText("CV:");

        Validade.setText("Validade:");

        Bandeira.setText("Bandeira:");

        try {
            NumeroCartaoCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            CVCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ValidadeCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ContinuarDadosBancarios.setText("Continuar");
        ContinuarDadosBancarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarDadosBancariosActionPerformed(evt);
            }
        });

        VoltarDadosBancarios.setText("Voltar");
        VoltarDadosBancarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarDadosBancariosActionPerformed(evt);
            }
        });

        BandeiraCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "MasterCard", "Elo", "Visa", "HiperCard", "AmericanExpress" }));
        BandeiraCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandeiraCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(CV)
                    .addComponent(Validade)
                    .addComponent(Bandeira))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BandeiraCli, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ValidadeCli, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CVCli, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NumeroCartaoCli, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VoltarDadosBancarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContinuarDadosBancarios)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NumeroCartaoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CV)
                    .addComponent(CVCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Validade)
                    .addComponent(ValidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bandeira)
                    .addComponent(BandeiraCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoltarDadosBancarios)
                    .addComponent(ContinuarDadosBancarios))
                .addContainerGap())
        );

        SeCadastro.addTab("Dados Bancários", jPanel1);

        Nome.setText("Nome:");

        CPF.setText("CPF:");

        DataNascimento.setText("Data de Nascimento:");

        Confirmar.setText("Confirmar");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        VoltarCadCli.setText("Voltar");
        VoltarCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarCadCliActionPerformed(evt);
            }
        });

        Telefone.setText("Telefone:");

        try {
            DataNascimentoCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            CPFCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TelefoneCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+## (##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        Email.setText("Email:");

        javax.swing.GroupLayout CadClienteLayout = new javax.swing.GroupLayout(CadCliente);
        CadCliente.setLayout(CadClienteLayout);
        CadClienteLayout.setHorizontalGroup(
            CadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadClienteLayout.createSequentialGroup()
                        .addGroup(CadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeCli)
                            .addComponent(CPFCli)
                            .addComponent(DataNascimentoCli)
                            .addComponent(TelefoneCli, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(EmailCli)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(VoltarCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Confirmar)))
                .addContainerGap())
        );
        CadClienteLayout.setVerticalGroup(
            CadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadClienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(CadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(NomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPF)
                    .addComponent(CPFCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataNascimento)
                    .addComponent(DataNascimentoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(CadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefone)
                    .addComponent(TelefoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(EmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(CadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoltarCadCli)
                    .addComponent(Confirmar))
                .addGap(15, 15, 15))
        );

        SeCadastro.addTab("Dados Básicos", CadCliente);

        setJMenuBar(MnCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SeCadastro)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SeCadastro)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limparCamposEntrada() {
        NumeroCli.setText("");
        RuaCli.setText("");
        BairroCli.setText("");
        CidadeCli.setText("");
        PaisCli.setText("");
        UFCli.setText("");
        CepCli.setText("");
        NumeroCartaoCli.setText("");
        CVCli.setText("");
        ValidadeCli.setText("");
        BandeiraCli.setSelectedIndex(0);
        NomeCli.setText("");
        CPFCli.setText("");
        DataNascimentoCli.setText("");
        TelefoneCli.setText("");
        EmailCli.setText("");
    }
    private void BandeiraCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandeiraCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BandeiraCliActionPerformed

    private void VoltarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarEnderecoActionPerformed
        this.dispose();

    }//GEN-LAST:event_VoltarEnderecoActionPerformed

    private void ContinuarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarEnderecoActionPerformed
        SeCadastro.setSelectedIndex(1);
    }//GEN-LAST:event_ContinuarEnderecoActionPerformed

    private void ContinuarDadosBancariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarDadosBancariosActionPerformed
        SeCadastro.setSelectedIndex(2);
    }//GEN-LAST:event_ContinuarDadosBancariosActionPerformed

    private void VoltarDadosBancariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarDadosBancariosActionPerformed
        SeCadastro.setSelectedIndex(0);
    }//GEN-LAST:event_VoltarDadosBancariosActionPerformed

    private void VoltarCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarCadCliActionPerformed
        SeCadastro.setSelectedIndex(1);
    }//GEN-LAST:event_VoltarCadCliActionPerformed


    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed

        validador.limparMensagensErro();

// Validação do campo NumeroCli (deve ser um número inteiro)
        validador.validarNumeroInteiro(NumeroCli.getText(), "Número");

// Validação dos campos de texto (Rua, Bairro, Cidade, País)
        validador.validarTexto(RuaCli.getText(), "Rua");
        validador.validarTexto(BairroCli.getText(), "Bairro");
        validador.validarTexto(CidadeCli.getText(), "Cidade");
        validador.validarTexto(PaisCli.getText(), "País");

// Validação dos campos UF e CEP (devem ser números inteiros)
        validador.validarTexto(UFCli.getText(), "UF");
        String cepTexto = CepCli.getText().replace("-", "");

// Valide o campo CEP (deve ser um número inteiro)
        validador.validarNumeroInteiro(cepTexto, "CEP");

// Validação dos dados bancários
        validador.validarTexto(NumeroCartaoCli.getText(), "Número do Cartão");
        validador.validarTexto(CVCli.getText(), "CV");

// Validação da data de validade (formato MM/AA)
        String validade = ValidadeCli.getText();
        if (!validade.matches("\\d{2}/\\d{2}")) {
            validador.adicionarMensagemErro("Formato de validade inválido. Use MM/AA.");
        } else {
            String[] partesValidade = validade.split("/");
            int mes = Integer.parseInt(partesValidade[0]);
            int ano = Integer.parseInt(partesValidade[1]);
            if (mes < 1 || mes > 12 || ano < 0 || ano > 99) {
                validador.adicionarMensagemErro("Data de validade inválida.");
            }
        }

// Validação da seleção da bandeira
        if (BandeiraCli.getSelectedIndex() == 0) {
            validador.adicionarMensagemErro("Selecione uma bandeira.");
        }

// Validação dos dados básicos
        validador.validarTexto(NomeCli.getText(), "Nome");

// Validação do CPF
        String cpf = CPFCli.getText().replace(".", "").replace("-", "").replaceAll(" ", "");

        int TamCpf = cpf.length();

        if (cpf.equals("") || TamCpf != 11) {

            validador.adicionarMensagemErro("CPF inválido.");
        }

// Validação da data de nascimento
        String dataNascimento = DataNascimentoCli.getText();
        if (!dataNascimento.matches("\\d{2}/\\d{2}/\\d{4}")) {
            validador.adicionarMensagemErro("Data de Nascimento inválida. Use DD/MM/AAAA.");
        }

// Validação do telefone
        String telefone = TelefoneCli.getText().replaceAll("[^0-9]", "");
        if (telefone.length() < 10) {
            validador.adicionarMensagemErro("Telefone inválido.");
        }

// Validação do email (adicionar sua própria validação se necessário)
        if (validador.temErros()) {
            // Exiba mensagens de erro se houver algum erro de validação
            List<String> mensagensErro = validador.getMensagensErro();
            String mensagem = String.join("\n", mensagensErro);
            JOptionPane.showMessageDialog(this, mensagem, "Erro", JOptionPane.ERROR_MESSAGE);

            // Limpe os campos de entrada mesmo em caso de erro
            limparCamposEntrada();
        } else {
            // Lógica de cadastro bem-sucedido aqui...

            // Após o cadastro bem-sucedido, limpe as caixas de entrada
            limparCamposEntrada();

            // Exiba uma mensagem de sucesso
            JOptionPane.showMessageDialog(null, "CLIENTE CADASTRADO!!!");
            this.dispose();

            // Você pode decidir se deseja fechar a janela ou fazer outra ação aqui...
        }

    }//GEN-LAST:event_ConfirmarActionPerformed

    private void BairroCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BairroCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BairroCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bairro;
    private javax.swing.JTextField BairroCli;
    private javax.swing.JLabel Bandeira;
    private javax.swing.JComboBox<String> BandeiraCli;
    private javax.swing.JLabel CEP;
    private javax.swing.JLabel CPF;
    private javax.swing.JFormattedTextField CPFCli;
    private javax.swing.JLabel CV;
    private javax.swing.JFormattedTextField CVCli;
    private javax.swing.JPanel CadCliente;
    private javax.swing.JFormattedTextField CepCli;
    private javax.swing.JLabel Cidade;
    private javax.swing.JTextField CidadeCli;
    private javax.swing.JButton Confirmar;
    private javax.swing.JButton ContinuarDadosBancarios;
    private javax.swing.JButton ContinuarEndereco;
    private javax.swing.JLabel DataNascimento;
    private javax.swing.JFormattedTextField DataNascimentoCli;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailCli;
    private javax.swing.JPanel EnderecoCli;
    private javax.swing.JMenuBar MnCadastro;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField NomeCli;
    private javax.swing.JLabel Numero;
    private javax.swing.JFormattedTextField NumeroCartaoCli;
    private javax.swing.JTextField NumeroCli;
    private javax.swing.JLabel Pais;
    private javax.swing.JTextField PaisCli;
    private javax.swing.JLabel Rua;
    private javax.swing.JTextField RuaCli;
    private javax.swing.JTabbedPane SeCadastro;
    private javax.swing.JLabel Telefone;
    private javax.swing.JFormattedTextField TelefoneCli;
    private javax.swing.JLabel UF;
    private javax.swing.JFormattedTextField UFCli;
    private javax.swing.JLabel Validade;
    private javax.swing.JFormattedTextField ValidadeCli;
    private javax.swing.JButton VoltarCadCli;
    private javax.swing.JButton VoltarDadosBancarios;
    private javax.swing.JButton VoltarEndereco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
